### ISSUE TITLE
Add new libary

### ISSUE THREAD

**Issue by Sabonar** [diablomedia/useragent-parser-comparison#133]
Hello, can you please add this libary in the comparison list. 
https://github.com/mimmi20/BrowserDetector

**Comment by Sabonar** [comment]
I think i just fucked up

**Comment by jaydiablo** [comment]
@Sabonar we have version 5 of that lib here: https://github.com/diablomedia/useragent-parser-comparison/tree/master/parsers/browser-detector-php-5

Might not be in the README though (need to update that).
