### ISSUE TITLE
update browscap.ini for all parsers

### ISSUE THREAD

**Issue by mimmi20** [diablomedia/useragent-parser-comparison#154]
Actually each browscap based parser downloads the browscap.ini file for itself during the install/update process.

The browscap.ini files should be downloaded (or generated) before updating the parsers and shared.

**Comment by jaydiablo** [comment]
I'd like to keep the parsers independent of eachother, but I think we could effectively achieve this by having them use a shared download location so at least each browscap.ini file only has to be downloaded once.
